"""
浏览器驱动抽象：为 Playwright 实现与未来 CDP/其他驱动留出插拔点。
"""
# @file purpose: Define browser driver interface (abstract).

from typing import Any, Protocol


class BrowserDriver(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def new_context(self) -> Any: ...
    async def close_context(self, ctx: Any) -> None: ...
    async def goto(self, ctx: Any, url: str) -> None: ...
    async def click(self, ctx: Any, selector: str) -> None: ...
    async def type_text(self, ctx: Any, selector: str, text: str) -> None: ...
    async def wait_for(self, ctx: Any, selector: str, timeout_ms: int | None = None) -> None: ...
    async def text_content(self, ctx: Any, selector: str) -> str | None: ...
    async def screenshot(self, ctx: Any, path: str) -> None: ...
